import type { Metadata } from "next";
// import { Inter } from "next/font/google"; // ⛔️ 구글 폰트 에러 방지
import "./globals.css";
import ReactQueryProvider from "./providers/ReactQueryProvider";
import { Toaster } from "@/components/atoms/Toast/Toaster"; // 🔥 추가

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "K&N 부동산 - 테스트페이지",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <ReactQueryProvider>
          {children}
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
